"""
Adversarial IoT Environment for Blue Team Training.

This module implements the Gymnasium environment where the RL agent
(Blue Team) learns to defend against attacks generated by the Attack
Sequence Generator (Red Team).

Key Design
----------
- **Hidden state**. The attack stage is *not* directly observable. The agent
  receives a sliding window of realized feature vectors (and, optionally,
  their first-order deltas).
- **Action space**. ``Discrete(5)`` force-continuum:
  ``OBSERVE=0`` < ``LOG=1`` < ``THROTTLE=2`` < ``BLOCK=3`` < ``ISOLATE=4``.
- **Reward**. *Stage-action proportionality* relative to the IoTWarden
  recommended-action mapping (see :func:`_recommended_action`):

      R_t = R_proportional - C_action - P_overreact - P_underreact +
            R_progress_blocked

  This replaces the previous action-vs-previous-action heuristic; see
  ``docs/results/environment/PLAN.md`` (B2 fix).
- **Lifecycle (environment-design v2).**
    - The episode runs for **at least** ``min_episode_length`` steps and at
      most ``max_steps`` (truncation). Choosing BLOCK or ISOLATE on an
      active attack does *not* end the episode anymore.
    - Instead, with probability ``p_defender_deescalation`` (default 0.6),
      the env *resets the attack to BENIGN* on the next step, modeling the
      defender successfully neutralizing the threat. This produces a
      genuine de-escalation signal that the LSTM Red Team's upper-triangular
      transition matrix cannot generate on its own (B3 fix).
    - When the attack reaches IMPACT, the agent is granted exactly one final
      defensive turn and the episode terminates regardless of
      ``min_episode_length``.
- **MTTC** (Mean Time To Compromise). Tracked per-episode via
  ``info["mttc_steps"]`` and ``info["compromised"]`` (B5 fix).
"""

import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional, Union

import gymnasium as gym
import numpy as np
import torch
from gymnasium import spaces

from src.generator.attack_sequence_generator import AttackSequenceGenerator
from src.utils.label_mapper import KillChainStage
from src.utils.realization_engine import RealizationEngine

# Optional stage-detector loading (lazy to avoid heavy import when unused)
_StageDetector = Any  # forward ref for type hints

logger = logging.getLogger(__name__)

# =============================================================================
# ACTION SPACE: Force Continuum
# =============================================================================

ACTION_NAMES: list[str] = [
    "OBSERVE",  # Level 0: Passive monitoring
    "LOG",  # Level 1: Enhanced logging
    "THROTTLE",  # Level 2: Rate limiting
    "BLOCK",  # Level 3: Block connections
    "ISOLATE",  # Level 4: System isolation
]

ACTION_COSTS: list[float] = [
    0.0,  # OBSERVE: No cost
    0.1,  # LOG: Minimal impact
    0.3,  # THROTTLE: Some disruption
    0.5,  # BLOCK: Significant impact
    0.8,  # ISOLATE: Major disruption
]


def get_action_cost(action: int) -> float:
    """Get the cost of a defensive action.

    Args:
        action: Action index (0-4).

    Returns:
        Cost of the action.
    """
    return ACTION_COSTS[action]


def _load_stage_detector(path: Path) -> Any:
    """Load a frozen stage detector from ``path``.

    Supports ``.pt`` (PyTorch :class:`StageDetector`) and ``.joblib``
    (sklearn :class:`RandomForestClassifier`) checkpoints.  Returns an
    object with a ``predict(features_2d) -> stage_ids`` method.
    """
    suffix = path.suffix.lower()
    if suffix == ".pt":
        from src.detector.stage_detector import StageDetector

        det = StageDetector.from_checkpoint(path)
        # wrap so caller sees uniform ``predict``
        return _DetectorWrapper(det.predict)
    if suffix in (".joblib", ".pkl", ".pickle"):
        import joblib

        clf = joblib.load(path)
        return _DetectorWrapper(clf.predict)
    raise ValueError(
        f"Unsupported stage-detector checkpoint format: {path} "
        f"(expected .pt or .joblib)"
    )


class _DetectorWrapper:
    """Thin wrapper unifying StageDetector.predict and sklearn.predict."""

    def __init__(self, predict_fn):
        self._predict = predict_fn

    def predict(self, X: np.ndarray) -> np.ndarray:
        return self._predict(X)


def get_action_name(action: int) -> str:
    """Get the name of a defensive action.

    Args:
        action: Action index (0-4).

    Returns:
        Name of the action.
    """
    return ACTION_NAMES[action]


# =============================================================================
# RECOMMENDED-ACTION MAPPING (IoTWarden-aligned, see PLAN §3.1 step 2)
# =============================================================================
#
# stage  -> recommended action
#  0  BENIGN     -> 0  OBSERVE
#  1  RECON      -> 1  LOG
#  2  ACCESS     -> 2  THROTTLE
#  3  MANEUVER   -> 3  BLOCK
#  4  IMPACT     -> 4  ISOLATE
#
# This is the canonical mapping used by IoTWarden (Bhattacharjee et al., 2023,
# Fig. 4) and the policy the new reward function grades against. An action
# within ±1 of the recommended level earns ``reward_proportional``; ±2 or
# more earns ``-penalty_disproportionate``.

_RECOMMENDED_ACTION_BY_STAGE: list[int] = [0, 1, 2, 3, 4]


def _recommended_action(stage: int) -> int:
    """Return the IoTWarden-aligned recommended action for ``stage``."""
    return _RECOMMENDED_ACTION_BY_STAGE[stage]


# =============================================================================
# ENVIRONMENT CONFIGURATION
# =============================================================================


@dataclass
class AdversarialEnvConfig:
    """Configuration for the Adversarial Environment.

    See ``docs/results/environment/PLAN.md`` for the rationale behind every reward
    constant. Most fields are tunable in Phase 8 (sensitivity ablation); the
    defaults below are the values used to lock the environment-design exit gates.

    Lifecycle attributes
    --------------------
    max_steps:
        Hard cap on episode length. Truncation fires once
        ``step_count >= max_steps``.
    min_episode_length:
        The episode is *guaranteed* to run for at least this many steps. The
        agent cannot end the episode early via BLOCK/ISOLATE; only IMPACT can
        terminate before this many steps. environment-design exit gate G3.2 requires
        median episode length ≥ 15 with random actions.
    p_defender_deescalation:
        On any step where the agent picks BLOCK or ISOLATE *and* the attack
        is currently at ACCESS or above, the env resets the attack to BENIGN
        on the next step with this probability. The remaining probability
        leaves the LSTM Red Team in charge as usual. ``0.6`` is the default;
        Phase 8 sweeps this value.

    Reward attributes
    -----------------
    action_cost_scale:
        Multiplier applied to ``ACTION_COSTS[action]``. Allows global
        scaling of how "expensive" actions are without rewriting the table.
    reward_proportional:
        Bonus when ``|action − recommended_action(stage)| ≤ 1``. The agent
        gets this every step where it is "close enough" to the
        IoTWarden-mapped recommended action.
    penalty_disproportionate:
        Symmetric penalty when ``|action − recommended_action(stage)| ≥ 2``.
    impact_penalty, penalty_missed_impact:
        Applied on the final IMPACT step. ``impact_penalty`` is unconditional;
        ``penalty_missed_impact`` is added when the agent under-reacts
        (OBSERVE/LOG).
    penalty_overreact_benign, penalty_block_benign, penalty_block_recon:
        Asymmetric penalties for cocked-trigger policies. Kept from v1
        because Phase 0 confirmed they meaningfully suppress the
        "always-BLOCK" degenerate strategy.
    defense_success_bonus:
        Earned (a) on the IMPACT step when the agent picks BLOCK/ISOLATE,
        and (b) when the env de-escalates from MANEUVER/IMPACT to BENIGN
        because of an agent-driven defense action.
    impact_is_terminal:
        If ``True`` (default, environment-design frozen contract), the episode
        terminates the same step the env transitions to IMPACT, and the
        terminal reward is applied inline against whatever action the
        agent took *that same step* (which was chosen at the previous,
        non-IMPACT stage).

        If ``False`` (ablation D7.3, F9 ablation axis), the env transitions
        to IMPACT but does NOT terminate that step. The agent's *next*
        action is taken as the explicit IMPACT-row decision, then
        :meth:`_step_at_impact` runs with that action and the env
        terminates. This decouples "the step where IMPACT arrives" from
        "the step where the agent picks an IMPACT response", giving the
        agent an unconfounded IMPACT-row decision. Default ``True``
        preserves the environment-design/4/5/6 frozen contract byte-for-byte.
    """

    # Lifecycle
    max_steps: int = 500
    min_episode_length: int = 20
    p_defender_deescalation: float = 0.6
    window_size: int = 5
    include_deltas: bool = True
    num_actions: int = 5
    impact_is_terminal: bool = True

    # Non-monotonic attacker stress-test (review 2.4.3)
    # After sampling the next stage from the generator, independently
    # override it with a retreat to a random earlier stage with this
    # probability.  Default 0.0 preserves the monotonic-attacker contract.
    retreat_prob: float = 0.0

    # Stage-prediction ablation (review 2.4.1)
    # If non-None, the env loads a frozen stage detector and (optionally)
    # appends its predicted stage to the observation vector.
    stage_detector_path: Optional[str] = None
    include_stage_pred: bool = False

    # Reward — proportionality core (B2 fix)
    action_cost_scale: float = 1.0
    reward_proportional: float = 5.0
    penalty_disproportionate: float = 5.0

    # Reward — terminal & extreme cases
    impact_penalty: float = 200.0
    penalty_missed_impact: float = 150.0
    # The mitigation bonus is intentionally calibrated so that a *correct*
    # IMPACT response (ISOLATE) net-rewards the agent: -impact_penalty +
    # defense_success_bonus = -200 + 250 = +50. This makes the optimal
    # policy strictly better than the do-nothing baseline and lets the
    # G3.4 exit gate hold (recommended-action mean reward > 0). The same
    # bonus is awarded on defender-driven de-escalations during normal
    # gameplay (with action >= BLOCK at ACCESS+). See PLAN §B6.
    defense_success_bonus: float = 250.0

    # Reward — benign-traffic guardrails
    reward_benign_passive: float = 10.0
    penalty_overreact_benign: float = 50.0
    penalty_block_benign: float = 100.0
    penalty_block_recon: float = 50.0

    # Lagrangian FPR penalty (review 2.2 / Direction 6)
    # At episode end, subtract beta * (benign_blocks / benign_steps).
    # beta=0.0 disables the penalty (default, preserves prior behaviour).
    fpr_penalty_beta: float = 0.0


# =============================================================================
# ADVERSARIAL ENVIRONMENT
# =============================================================================


class AdversarialIoTEnv(gym.Env):
    """Gymnasium environment for adversarial IoT defense training.

    This environment implements a partially observable Markov decision
    process where the agent observes realized network features but
    cannot directly see the underlying attack stage.

    Red Team (Attack Sequence Generator):
        - Controls attack progression through Kill Chain stages
        - Uses LSTM to generate realistic attack sequences

    Blue Team (RL Agent):
        - Observes window of feature vectors
        - Takes discrete defensive actions
        - Receives reward based on defense effectiveness

    Observation Space:
        Box of shape (window_size * num_features,) or
        (window_size * num_features * 2,) when delta features are enabled.

    Action Space:
        Discrete(5): OBSERVE, LOG, THROTTLE, BLOCK, ISOLATE

    Example:
        >>> env = AdversarialIoTEnv(generator_path, dataset_path)
        >>> obs, info = env.reset()
        >>> obs, reward, terminated, truncated, info = env.step(2)

    .. warning::
       **Direct construction contract (Step-3 F2 / Step-8 doc-fix).**
       Calling ``AdversarialIoTEnv(generator_path, dataset_path, ...)``
       directly builds a non-split-aware ``RealizationEngine`` (the
       constructor at L305-ish below instantiates ``RealizationEngine(
       dataset_path)`` with no ``split_manifest`` / ``allowed_indices``
       argument). This means the engine samples from the *full* row
       pool — it does NOT honour the dataset-prep OOD-exclusion or
       ``split="train"`` invariants Phases 4–7 depend on.

       **Production callers must use one of**:

       - ``src.blue_team.env_factory.make_train_env(...)`` (sets
         ``split="train", exclude_ood=True`` and monkey-patches the
         engine post-construction via ``env._realization_engine =
         engine``); or
       - ``src.blue_team.env_factory.make_eval_env(...)`` (caller
         supplies the eval split — typically ``"val_balanced"`` for
         blue-team eval or ``"test_balanced"`` for benchmark / ablation).

       Direct ``AdversarialIoTEnv(...)`` construction is reserved for
       synthetic-data unit tests (see ``tests/test_adversarial_env.py``)
       and the hand-rolled smoke probe in
       ``scripts/benchmark/run_test_eval.py:_roll_deterministic`` (RF-
       Acting feature-dim probe). A future refactor could add an
       ``engine: Optional[RealizationEngine] = None`` injection seam
       to ``__init__`` so the factory could pass the engine in
       directly (eliminating the ``# type: ignore[attr-defined]``
       monkey-patch in ``env_factory.py``); deferred to post-thesis.
    """

    metadata = {"render_modes": ["human"]}

    def __init__(
        self,
        generator_path: Union[str, Path],
        dataset_path: Union[str, Path],
        config: Optional[AdversarialEnvConfig] = None,
        render_mode: Optional[str] = None,
        device: str = "cpu",
    ) -> None:
        """Initialize the Adversarial Environment.

        Args:
            generator_path: Path to trained Attack Sequence Generator.
            dataset_path: Path to processed dataset for realization.
            config: Environment configuration.
            render_mode: Rendering mode (optional).
            device: Device for generator inference.
        """
        super().__init__()

        self._config = config or AdversarialEnvConfig()
        self._render_mode = render_mode
        requested_device = torch.device(device)

        # NOTE: AttackSequenceGenerator relies on nn.Embedding, which can raise
        # intermittent runtime errors on some PyTorch + Apple MPS combinations
        # during inference. Keep environment-side generator inference on CPU for
        # robustness while allowing RL policy training to proceed.
        if requested_device.type == "mps":
            logger.warning(
                "MPS requested for environment generator inference; "
                "falling back to CPU for AttackSequenceGenerator stability."
            )
            self._device = torch.device("cpu")
        else:
            self._device = requested_device

        # Load Attack Sequence Generator (Red Team)
        generator_path = Path(generator_path)
        model_file = generator_path / "attack_sequence_generator.pth"
        self._generator = AttackSequenceGenerator.load(model_file, device=self._device)
        self._generator.eval()

        # Load Realization Engine (for feature sampling)
        dataset_path = Path(dataset_path)
        self._realization_engine = RealizationEngine(dataset_path)

        # Get feature dimension from dataset
        self._num_features = self._realization_engine.num_features

        # Load optional frozen stage detector for stage-prediction ablation
        self._stage_detector: Any = None
        if self._config.stage_detector_path is not None:
            self._stage_detector = _load_stage_detector(
                Path(self._config.stage_detector_path)
            )

        # Define observation space: flattened window of features (optionally with deltas)
        obs_multiplier = 2 if self._config.include_deltas else 1
        obs_dim = self._config.window_size * self._num_features * obs_multiplier
        if self._config.include_stage_pred:
            if self._stage_detector is None:
                raise ValueError(
                    "include_stage_pred=True requires stage_detector_path to be set"
                )
            obs_dim += self._config.num_actions  # one-hot appended stage
        self.observation_space = spaces.Box(
            low=-np.inf,
            high=np.inf,
            shape=(obs_dim,),
            dtype=np.float32,
        )

        # Define action space: force continuum levels
        self.action_space = spaces.Discrete(self._config.num_actions)

        # Episode state (initialized in reset)
        self._step_count: int = 0
        self._current_attack_stage: int = 0
        self._attack_history: list[int] = []
        self._observation_window: list[np.ndarray] = []
        self._last_action: int = 0
        self._rng: Optional[np.random.Generator] = None
        # environment-design: MTTC tracking & defender-driven de-escalation
        self._first_attack_step: Optional[int] = None
        self._compromise_step: Optional[int] = None
        self._defender_deescalations: int = 0
        # FPR-penalty accumulator (review 2.2 / Direction 6)
        self._benign_steps: int = 0
        self._benign_blocks: int = 0

        logger.info(
            f"AdversarialIoTEnv initialized: "
            f"obs_shape={self.observation_space.shape}, "
            f"actions={self._config.num_actions}, "
            f"features={self._num_features}"
        )

    # =========================================================================
    # Gymnasium API
    # =========================================================================

    def reset(
        self,
        *,
        seed: Optional[int] = None,
        options: Optional[dict[str, Any]] = None,
    ) -> tuple[np.ndarray, dict[str, Any]]:
        """Reset the environment to start a new episode.

        Args:
            seed: Random seed for reproducibility.
            options: Additional options (unused).

        Returns:
            Tuple of (observation, info).
        """
        super().reset(seed=seed)

        # Setup RNG
        if seed is not None:
            self._rng = np.random.default_rng(seed)
            # Also seed the realization engine
            self._realization_engine._rng = np.random.default_rng(seed)
            # And set torch seed for generator
            torch.manual_seed(seed)
            np.random.seed(seed)
        else:
            self._rng = np.random.default_rng()

        # Reset episode state
        self._step_count = 0
        self._last_action = 0
        self._first_attack_step = None
        self._compromise_step = None
        self._defender_deescalations = 0
        self._benign_steps = 0
        self._benign_blocks = 0

        # Initialize attack sequence
        # Start with BENIGN or low-level attack
        self._current_attack_stage = 0  # BENIGN
        self._attack_history = [self._current_attack_stage]

        # Initialize observation window with BENIGN features
        self._observation_window = []
        for _ in range(self._config.window_size):
            features = self._realization_engine.sample(KillChainStage.BENIGN)
            self._observation_window.append(features)

        # Build initial observation
        observation = self._build_observation()

        # Build info dict
        info = self._build_info()

        return observation, info

    def step(
        self,
        action: int,
    ) -> tuple[np.ndarray, float, bool, bool, dict[str, Any]]:
        """Execute one environment step.

        Lifecycle (environment-design v2):

        1. **IMPACT step.** If we entered this step already at IMPACT, this is
           the agent's final mitigation turn. Reward depends on action choice;
           the episode terminates regardless.
        2. **Decision-stage reward.** Reward is computed against
           ``decision_stage = previous_attack_stage`` and the IoTWarden
           recommended-action mapping. No dependence on the agent's previous
           action.
        3. **Attack progression.** The Red Team LSTM samples the next stage.
           When the agent chose BLOCK or ISOLATE at ACCESS+ stages, the env
           overrides this with a defender-driven de-escalation to BENIGN
           (with probability ``p_defender_deescalation``). On a successful
           override, ``defense_success_bonus`` is added to the reward.
        4. **Termination.** The episode terminates only when the new stage is
           IMPACT (the agent will get one final IMPACT step on the next
           call) — but for backwards compatibility we mark ``terminated`` on
           that step too via ``_check_terminated``. Truncation fires at
           ``max_steps``.
        """
        assert self.action_space.contains(action), f"Invalid action: {action}"

        self._step_count += 1
        previous_attack_stage = self._current_attack_stage

        # 1) Final mitigation turn at IMPACT — fixed reward shape, terminate.
        if previous_attack_stage == KillChainStage.IMPACT.value:
            return self._step_at_impact(action)

        # 2) Reward for this step is decided by stage at decision time.
        reward = self._calculate_reward(action, previous_attack_stage)
        self._track_benign_fpr(action, previous_attack_stage)

        # 3) Advance the attack — possibly overriding with defender-driven
        # de-escalation if the agent chose a strong action at ACCESS+.
        agent_forced_deescalation = self._maybe_defender_deescalation(action, previous_attack_stage)
        if agent_forced_deescalation:
            reward += self._config.defense_success_bonus
            outcome = "defended"
        else:
            self._advance_attack()
            outcome = "ongoing"

        # Lifecycle-floor clamp: real-world IMPACT requires time-to-execute.
        # Until the agent has had its grace period, the LSTM is not allowed
        # to short-circuit the kill chain by jumping straight to IMPACT.
        # Concretely: any IMPACT transition before ``min_episode_length`` is
        # downgraded to MANEUVER. This both gives the agent a fair chance to
        # learn the multi-stage dynamics *and* matches the IoTWarden-style
        # threat model in which IMPACT is the consummation of MANEUVER, not
        # an instantaneous transition from RECON.
        if (
            self._current_attack_stage == KillChainStage.IMPACT.value
            and self._step_count < self._config.min_episode_length
        ):
            self._current_attack_stage = KillChainStage.MANEUVER.value
            # Keep the history consistent: replace the last entry rather than
            # appending a parallel one (the LSTM only sees the visible chain).
            if self._attack_history:
                self._attack_history[-1] = self._current_attack_stage

        # MTTC bookkeeping — see _build_info() for the consumed fields.
        if (
            self._first_attack_step is None
            and self._current_attack_stage != KillChainStage.BENIGN.value
        ):
            self._first_attack_step = self._step_count
        if (
            self._compromise_step is None
            and self._current_attack_stage == KillChainStage.IMPACT.value
        ):
            self._compromise_step = self._step_count

        # 4) Refresh the observation window with a sample drawn from the
        # *new* stage. This is intentional: the agent's *next* observation
        # already reflects whatever the attacker just did.
        new_features = self._realization_engine.sample(KillChainStage(self._current_attack_stage))
        self._observation_window.pop(0)
        self._observation_window.append(new_features)
        self._last_action = action

        # Termination: only IMPACT triggers it, and only after the
        # min_episode_length grace period has elapsed (otherwise the agent
        # never sees a multi-stage trajectory).
        impact_arrived = (
            self._current_attack_stage == KillChainStage.IMPACT.value
            and self._step_count >= self._config.min_episode_length
        )
        if impact_arrived and self._config.impact_is_terminal:
            # environment-design frozen contract (default).
            # Apply the terminal IMPACT penalty inline. The kill chain has
            # consummated this step; we do *not* hand the agent a separate
            # "_step_at_impact" turn for OBSERVE/LOG -> the missed defense
            # is precisely what the IMPACT penalty was designed to punish.
            # Strong defenses (BLOCK/ISOLATE) earn the partial mitigation
            # bonus; weak defenses (OBSERVE/LOG) take the missed-impact hit.
            reward -= self._config.impact_penalty
            if action >= 3:
                reward += self._config.defense_success_bonus
                outcome = "impact_mitigated"
            elif action <= 1:
                reward -= self._config.penalty_missed_impact
                outcome = "impact_missed"
            else:
                outcome = "compromised"
            terminated = True
        else:
            # Either IMPACT has not arrived OR impact_is_terminal=False.
            # When False and IMPACT just arrived this step, do NOT terminate
            # and do NOT apply the inline terminal reward — the agent will
            # get an explicit IMPACT-row decision on the *next* step via
            # ``_step_at_impact`` (path 1 at the top of step()). The
            # "ongoing"/"defended" outcome label set above is preserved
            # so the F9 ablation sees this step as a normal pre-IMPACT
            # step that *just happened* to land on IMPACT.
            terminated = False
        truncated = self._step_count >= self._config.max_steps

        if terminated or truncated:
            reward = self._apply_episode_fpr_penalty(reward)

        observation = self._build_observation()
        info = self._build_info()
        info["outcome"] = outcome
        return observation, reward, terminated, truncated, info

    # ------------------------------------------------------------------ helpers

    def _step_at_impact(self, action: int) -> tuple[np.ndarray, float, bool, bool, dict[str, Any]]:
        """Handle the agent's final mitigation turn while the attack is at IMPACT."""
        action_cost = get_action_cost(action) * self._config.action_cost_scale
        reward = -(self._config.impact_penalty) - action_cost
        if action >= 3:  # BLOCK or ISOLATE — partial mitigation bonus
            reward += self._config.defense_success_bonus
            outcome = "impact_mitigated"
        elif action <= 1:  # OBSERVE or LOG — severe miss at IMPACT
            reward -= self._config.penalty_missed_impact
            outcome = "impact_missed"
        else:
            outcome = "impact_unmitigated"

        new_features = self._realization_engine.sample(KillChainStage.IMPACT)
        self._observation_window.pop(0)
        self._observation_window.append(new_features)
        self._last_action = action
        if self._compromise_step is None:
            self._compromise_step = self._step_count

        reward = self._apply_episode_fpr_penalty(reward)
        observation = self._build_observation()
        info = self._build_info()
        info["outcome"] = outcome
        return observation, reward, True, False, info

    def _apply_episode_fpr_penalty(self, reward: float) -> float:
        """Subtract terminal FPR penalty if fpr_penalty_beta > 0."""
        if self._config.fpr_penalty_beta <= 0.0:
            return reward
        if self._benign_steps == 0:
            return reward
        fpr = self._benign_blocks / self._benign_steps
        return reward - self._config.fpr_penalty_beta * fpr

    def _track_benign_fpr(self, action: int, previous_stage: int) -> None:
        """Increment benign-step / benign-block counters."""
        if previous_stage == KillChainStage.BENIGN.value:
            self._benign_steps += 1
            if action >= 3:  # BLOCK or ISOLATE
                self._benign_blocks += 1

    def _maybe_defender_deescalation(self, action: int, previous_stage: int) -> bool:
        """Return True iff the agent's action forced a stage reset to BENIGN.

        The override fires when the agent picks BLOCK or ISOLATE at an active
        ACCESS+ attack stage and the configured probability allows it. On a
        successful override the env replaces the natural attack progression
        for this step.
        """
        if action < 3:  # OBSERVE / LOG / THROTTLE never trigger
            return False
        if previous_stage < KillChainStage.ACCESS.value:
            return False
        assert self._rng is not None  # invariant after reset
        if self._rng.random() >= self._config.p_defender_deescalation:
            return False
        # Override the natural Red-Team transition.
        self._current_attack_stage = KillChainStage.BENIGN.value
        self._attack_history.append(self._current_attack_stage)
        self._defender_deescalations += 1
        return True

    def render(self) -> None:
        """Render the environment state."""
        if self._render_mode == "human":
            print(
                f"Step {self._step_count}: "
                f"Attack Stage = {KillChainStage(self._current_attack_stage).name}, "
                f"Last Action = {ACTION_NAMES[self._last_action]}"
            )

    def close(self) -> None:
        """Clean up environment resources."""
        pass

    # =========================================================================
    # Internal Methods
    # =========================================================================

    def _advance_attack(self) -> None:
        """Advance attack sequence using generator."""
        # Use generator to predict next attack stage
        if len(self._attack_history) >= 1:
            # Sample next stage from generator
            next_stage = self._generator.sample_next(
                self._attack_history[-5:],  # Use last 5 stages
                temperature=1.0,
            )
            # Non-monotonic stress-test: independently override with a
            # retreat to a random earlier stage (review 2.4.3).
            current_stage = self._current_attack_stage
            if (
                self._config.retreat_prob > 0.0
                and current_stage > 0
                and self._rng is not None
                and self._rng.random() < self._config.retreat_prob
            ):
                next_stage = int(self._rng.integers(0, current_stage))
            self._current_attack_stage = next_stage
            self._attack_history.append(next_stage)

    def _build_observation(self) -> np.ndarray:
        """Build observation from feature window."""
        # Stack window and flatten
        window_array = np.stack(self._observation_window, axis=0)
        if self._config.include_deltas:
            deltas = np.zeros_like(window_array)
            deltas[1:] = window_array[1:] - window_array[:-1]
            window_array = np.concatenate([window_array, deltas], axis=1)
        observation = window_array.flatten().astype(np.float32)
        # Stage-prediction ablation: append one-hot predicted stage
        if self._config.include_stage_pred:
            assert self._stage_detector is not None
            latest_row = self._observation_window[-1].reshape(1, -1)
            pred_stage = int(self._stage_detector.predict(latest_row)[0])
            one_hot = np.zeros(self._config.num_actions, dtype=np.float32)
            one_hot[pred_stage] = 1.0
            observation = np.concatenate([observation, one_hot])
        return observation

    def _build_info(self) -> dict[str, Any]:
        """Build info dictionary including environment-design telemetry.

        New keys (environment-design):

        - ``compromised`` (bool): True iff the attack reached IMPACT this
          episode.
        - ``mttc_steps`` (int | None): Steps from first non-BENIGN observation
          until IMPACT. ``None`` if the attack never started or never
          reached IMPACT.
        - ``defender_deescalations`` (int): How many times the defender
          successfully forced a stage reset to BENIGN this episode.
        - ``recommended_action`` (int): The IoTWarden-aligned recommended
          action for the *current* stage. Useful for downstream logging
          (e.g., proportionality histograms).
        """
        compromised = self._compromise_step is not None
        if compromised and self._first_attack_step is not None:
            mttc_steps: Optional[int] = self._compromise_step - self._first_attack_step
        else:
            mttc_steps = None

        return {
            "attack_stage": self._current_attack_stage,
            "attack_stage_name": KillChainStage(self._current_attack_stage).name,
            "step_count": self._step_count,
            "attack_history": list(self._attack_history),
            "last_action": self._last_action,
            "last_action_name": ACTION_NAMES[self._last_action],
            "compromised": compromised,
            "mttc_steps": mttc_steps,
            "first_attack_step": self._first_attack_step,
            "compromise_step": self._compromise_step,
            "defender_deescalations": self._defender_deescalations,
            "recommended_action": _recommended_action(self._current_attack_stage),
        }

    def _calculate_reward(self, action: int, previous_stage: int) -> float:
        """Reward for one non-IMPACT step.

        New formulation (environment-design, B2 fix). The reward depends *only* on the
        decision-time stage and the action — not on the agent's previous
        action. Components:

        - ``- C_action``: Cost of executing ``action`` (force-continuum scale).
        - Stage-specific guardrails on extreme errors (penalty_overreact_*,
          penalty_block_*, penalty_missed_impact at IMPACT — although the
          IMPACT branch is normally handled by ``_step_at_impact``).
        - ``+ reward_benign_passive`` when the agent picks OBSERVE/LOG on
          truly benign traffic — small but consistent positive signal so
          the "do nothing" baseline does not net to zero.
        - **Proportionality term (the core)**: ``+ reward_proportional`` when
          ``|action - recommended_action(stage)| ≤ 1``, else
          ``- penalty_disproportionate``. This is the policy the agent is
          ultimately graded against.

        Args:
            action: Defensive action taken (0..4).
            previous_stage: Attack stage at decision time (the stage the
                agent saw when it picked ``action``).

        Returns:
            Scalar reward.
        """
        decision_stage = int(previous_stage)
        reward = 0.0

        # 1) Cost of action.
        reward -= get_action_cost(action) * self._config.action_cost_scale

        # 2) Asymmetric guardrails on extreme errors.
        if decision_stage == KillChainStage.BENIGN.value and action >= 2:
            reward -= self._config.penalty_overreact_benign
            if action >= 3:
                reward -= self._config.penalty_block_benign
        elif decision_stage == KillChainStage.RECON.value and action >= 3:
            reward -= self._config.penalty_block_recon
        if decision_stage == KillChainStage.IMPACT.value and action <= 1:
            # Normally _step_at_impact handles IMPACT, but keep a safety
            # net so a pathological caller doesn't escape the penalty.
            reward -= self._config.penalty_missed_impact

        # 3) Positive signal for the canonical "do nothing on benign" case.
        if decision_stage == KillChainStage.BENIGN.value and action <= 1:
            reward += self._config.reward_benign_passive

        # 4) Stage-action proportionality — the new core (B2 fix).
        recommended = _recommended_action(decision_stage)
        proportionality_gap = abs(action - recommended)
        if proportionality_gap <= 1:
            reward += self._config.reward_proportional
        else:
            reward -= self._config.penalty_disproportionate

        return reward
