"""
Adversarial IoT Environment for Blue Team Training.

This module implements the Gymnasium environment where the RL agent
(Blue Team) learns to defend against attacks generated by a
first-order Markov attacker over kill-chain stages.

Key Design
----------
- **Hidden state**. The attack stage is *not* directly observable. The agent
  receives a sliding window of realized feature vectors (and, optionally,
  their first-order deltas).
- **Action space**. ``Discrete(5)`` force-continuum:
  ``OBSERVE=0`` < ``LOG=1`` < ``RESTRICT=2`` < ``BLOCK=3`` < ``ISOLATE=4``.
- **Reward**. *Stage-action proportionality* relative to the IoTWarden
  recommended-action mapping (see :func:`_recommended_action`):

      R_t = R_proportional - C_action - P_overreact - P_underreact +
            R_progress_blocked

  This replaces the previous action-vs-previous-action heuristic; see
  ``docs/results/environment/PLAN.md`` (B2 fix).
- **Lifecycle (environment-design v2).**
    - The episode runs for **at least** ``min_episode_length`` steps and at
      most ``max_steps`` (truncation). Choosing BLOCK or ISOLATE on an
      active attack does *not* end the episode anymore.
    - Instead, with probability ``p_defender_deescalation`` (default 0.6),
      the env *resets the attack to BENIGN* on the next step, modeling the
      defender successfully neutralizing the threat. This produces a
      genuine de-escalation signal that the Markov attacker's upper-triangular
      transition matrix cannot generate on its own (B3 fix).
    - When the attack reaches IMPACT, the agent is granted exactly one final
      defensive turn and the episode terminates regardless of
      ``min_episode_length``.
- **MTTC** (Mean Time To Compromise). Tracked per-episode via
  ``info["mttc_steps"]`` and ``info["compromised"]`` (B5 fix).
"""

import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Any, ClassVar, Optional, Union

import gymnasium as gym
import numpy as np
from gymnasium import spaces

from src.generator.markov_attacker import MarkovAttacker
from src.utils.label_mapper import KillChainStage
from src.utils.realization_engine import RealizationEngine

# Optional stage-detector loading (lazy to avoid heavy import when unused)
_StageDetector = Any  # forward ref for type hints

logger = logging.getLogger(__name__)

# =============================================================================
# ACTION SPACE: Force Continuum
# =============================================================================

ACTION_NAMES: list[str] = [
    "OBSERVE",  # Level 0: Passive monitoring
    "LOG",  # Level 1: Enhanced logging
    "RESTRICT",  # Level 2: Partial, reversible mitigation (rate-limit / constrain)
    "BLOCK",  # Level 3: Block connections
    "ISOLATE",  # Level 4: System isolation
]

ACTION_COSTS: list[float] = [
    0.0,  # OBSERVE: No cost
    0.1,  # LOG: Minimal impact
    0.3,  # RESTRICT: Some disruption
    0.5,  # BLOCK: Significant impact
    0.8,  # ISOLATE: Major disruption
]


def get_action_cost(action: int) -> float:
    """Get the cost of a defensive action.

    Args:
        action: Action index (0-4).

    Returns:
        Cost of the action.
    """
    return ACTION_COSTS[action]


def _load_stage_detector(path: Path) -> Any:
    """Load a frozen stage detector from ``path``.

    Supports ``.pt`` (PyTorch :class:`StageDetector`) and ``.joblib``
    (sklearn :class:`RandomForestClassifier`) checkpoints.  Returns an
    object with a ``predict(features_2d) -> stage_ids`` method.
    """
    suffix = path.suffix.lower()
    if suffix == ".pt":
        from src.detector.stage_detector import StageDetector

        det = StageDetector.from_checkpoint(path)
        # wrap so caller sees uniform ``predict``
        return _DetectorWrapper(det.predict)
    if suffix in (".joblib", ".pkl", ".pickle"):
        import joblib

        clf = joblib.load(path)
        return _DetectorWrapper(clf.predict)
    raise ValueError(
        f"Unsupported stage-detector checkpoint format: {path} " f"(expected .pt or .joblib)"
    )


class _DetectorWrapper:
    """Thin wrapper unifying StageDetector.predict and sklearn.predict."""

    def __init__(self, predict_fn):
        self._predict = predict_fn

    def predict(self, X: np.ndarray) -> np.ndarray:
        return self._predict(X)


def get_action_name(action: int) -> str:
    """Get the name of a defensive action.

    Args:
        action: Action index (0-4).

    Returns:
        Name of the action.
    """
    return ACTION_NAMES[action]


# =============================================================================
# RECOMMENDED-ACTION MAPPING (IoTWarden-aligned, see PLAN §3.1 step 2)
# =============================================================================
#
# stage  -> recommended action
#  0  BENIGN     -> 0  OBSERVE
#  1  RECON      -> 1  LOG
#  2  ACCESS     -> 2  RESTRICT
#  3  MANEUVER   -> 3  BLOCK
#  4  IMPACT     -> 4  ISOLATE
#
# This is the canonical mapping used by IoTWarden (Bhattacharjee et al., 2023,
# Fig. 4) and the policy the new reward function grades against. An action
# within ±1 of the recommended level earns ``reward_proportional``; ±2 or
# more earns ``-penalty_disproportionate``.

_RECOMMENDED_ACTION_BY_STAGE: list[int] = [0, 1, 2, 3, 4]


def _recommended_action(stage: int) -> int:
    """Return the IoTWarden-aligned recommended action for ``stage``."""
    return _RECOMMENDED_ACTION_BY_STAGE[stage]


# =============================================================================
# ENVIRONMENT CONFIGURATION
# =============================================================================


@dataclass
class AdversarialEnvConfig:
    """Configuration for the Adversarial Environment.

    See ``docs/results/environment/PLAN.md`` for the rationale behind every reward
    constant. Most fields are tunable in Ablation & Robustness (sensitivity ablation); the
    defaults below are the values used to lock the environment-design exit gates.

    Lifecycle attributes
    --------------------
    max_steps:
        Hard cap on episode length. Truncation fires once
        ``step_count >= max_steps``.
    min_episode_length:
        The episode is *guaranteed* to run for at least this many steps. The
        agent cannot end the episode early via BLOCK/ISOLATE; only IMPACT can
        terminate before this many steps. environment-design exit gate G3.2 requires
        median episode length ≥ 15 with random actions.
    p_defender_deescalation:
        On any step where the agent picks BLOCK or ISOLATE *and* the attack
        is currently at ACCESS or above, the env resets the attack to BENIGN
        on the next step with this probability. The remaining probability
        leaves the Markov attacker in charge as usual. ``0.6`` is the default;
        Ablation & Robustness sweeps this value.

    Reward attributes
    -----------------
    action_cost_scale:
        Multiplier applied to ``ACTION_COSTS[action]``. Allows global
        scaling of how "expensive" actions are without rewriting the table.
    reward_proportional:
        Bonus when ``|action − recommended_action(stage)| ≤ 1``. The agent
        gets this every step where it is "close enough" to the
        IoTWarden-mapped recommended action.
    penalty_disproportionate:
        Symmetric penalty when ``|action − recommended_action(stage)| ≥ 2``.
    impact_penalty, penalty_missed_impact:
        Applied on the final IMPACT step. ``impact_penalty`` is unconditional;
        ``penalty_missed_impact`` is added when the agent under-reacts
        (OBSERVE/LOG).
    penalty_overreact_benign, penalty_block_benign, penalty_block_recon:
        Asymmetric penalties for cocked-trigger policies. Kept from v1
        because preliminary calibration confirmed they meaningfully suppress the
        "always-BLOCK" degenerate strategy.
    defense_success_bonus:
        Earned (a) on the IMPACT step when the agent picks BLOCK/ISOLATE,
        and (b) when the env de-escalates from MANEUVER/IMPACT to BENIGN
        because of an agent-driven defense action.
    impact_is_terminal:
        If ``True`` (default, environment-design frozen contract), the episode
        terminates the same step the env transitions to IMPACT, and the
        terminal reward is applied inline against whatever action the
        agent took *that same step* (which was chosen at the previous,
        non-IMPACT stage).

        If ``False`` (ablation D7.3, F9 ablation axis), the env transitions
        to IMPACT but does NOT terminate that step. The agent's *next*
        action is taken as the explicit IMPACT-row decision, then
        :meth:`_step_at_impact` runs with that action and the env
        terminates. This decouples "the step where IMPACT arrives" from
        "the step where the agent picks an IMPACT response", giving the
        agent an unconfounded IMPACT-row decision. Default ``True``
        preserves the environment-design/4/5/6 frozen contract byte-for-byte.
    """

    # Lifecycle
    max_steps: int = 500
    min_episode_length: int = 20
    window_size: int = 5
    include_deltas: bool = True
    num_actions: int = 5
    impact_is_terminal: bool = True

    # =====================================================================
    # Tug-of-war attacker dynamics (environment-design v3, headline)
    # =====================================================================
    # The attacker's stage transition is driven by the *proportionality gap*
    # between the defender's action ``a`` and the stage-recommended action
    # ``rec = recommended(s)``, with ``gap = |a - rec|``:
    #
    #   gap == 0 (correctly calibrated force)  -> attacker DE-ESCALATES
    #                                             s -> max(0, s-1) w.p. p_down
    #   gap == 1 (adjacent / tolerable)        -> attacker HOLDS at s
    #   gap >= 2 (mis-calibrated force)        -> attacker ESCALATES
    #                                             s -> min(IMPACT, s+1) w.p. p_up
    #
    # The residual ``1 - p_*`` mass is a "hold" (nothing happens this step),
    # which deliberately prevents a degenerate, perfectly deterministic
    # lookup-table solution and keeps value planning under partial
    # observability meaningful. This ±1 graded structure mirrors the
    # proportionality reward exactly, so reward and dynamics are
    # self-consistent. ISOLATE (a=4) de-escalates *more reliably* than BLOCK
    # (a=3) — ``p_down_isolate`` >= ``p_down`` — giving the force ladder a
    # real effect gradient (not just a cost gradient) and removing the
    # weakly-dominated-action pathology of the v2 environment.
    #
    # Set ``tug_of_war=False`` to recover the v2 autonomous-Markov +
    # probabilistic-de-escalation dynamics (retained for the legacy ablation).
    tug_of_war: bool = True
    # Multi-rung autonomous onset from BENIGN (the attacker's own initiative,
    # independent of the defender). Each step at BENIGN the attacker opens a
    # campaign at RECON with probability ``p_onset`` or directly at ACCESS with
    # probability ``p_onset_access`` (a mid-chain campaign start); otherwise it
    # stays dormant. Multi-rung onset is what forces even a *correct* defender to
    # exercise ACCESS/MANEUVER-appropriate responses rather than pinning the
    # attacker at RECON and farming the proportional bonus. Set
    # ``p_onset_access=0.0`` to recover strict single-rung (RECON-only) onset,
    # which is retained as the pure-sequential threat-model ablation.
    p_onset: float = 0.35  # P(BENIGN -> RECON) per step
    p_onset_access: float = 0.10  # P(BENIGN -> ACCESS) per step (mid-chain start)
    p_down: float = 0.90  # P(de-escalate | correctly-calibrated force, d==0)
    p_up: float = 0.90  # P(escalate | under-force, d<=-1)
    p_down_isolate: float = 0.98  # P(de-escalate) when the force is ISOLATE (a=4)

    # Legacy v2 de-escalation probability (only used when tug_of_war=False).
    p_defender_deescalation: float = 0.6

    # Non-monotonic attacker stress-test (review 2.4.3)
    # After sampling the next stage from the generator, independently
    # override it with a retreat to a random earlier stage with this
    # probability.  Default 0.0 preserves the monotonic-attacker contract.
    retreat_prob: float = 0.0

    # Evasion-before-commit reactive attacker (the one adaptive-attacker axis).
    # When the defender has *just* applied force (BLOCK/ISOLATE) and the attacker
    # is still at a pre-trigger stage (RECON/ACCESS), it probabilistically stalls
    # (does not progress) in anticipation, with this probability. Unlike
    # ``retreat_prob`` (random, defender-independent) and de-escalation (resets to
    # BENIGN on force at ACCESS+), this is *coupled to the defender's action*.
    # Default 0.0 disables it.
    evasion_prob: float = 0.0

    # Explicit terminal reward for a prevented attack (attacker held below
    # IMPACT for the entire horizon). Calibrated to +50, mirroring the net
    # reward of a correct IMPACT mitigation (-impact_penalty +
    # defense_success_bonus = +50), so the security objective (prevention) and
    # the reward signal are aligned. This closes the latent farming loophole
    # where, with prevention_bonus=0, dragging the episode out to accumulate
    # per-step proportional rewards would be more profitable than ending it
    # early via prevention. The 0-vs-50 contrast is itself a
    # reward-mis-specification ablation cell.
    prevention_bonus: float = 50.0

    # Stage-prediction ablation (review 2.4.1)
    # If non-None, the env loads a frozen stage detector and (optionally)
    # appends its predicted stage to the observation vector.
    stage_detector_path: Optional[str] = None
    include_stage_pred: bool = False

    # Reward — proportionality core (B2 fix)
    action_cost_scale: float = 1.0
    reward_proportional: float = 5.0
    penalty_disproportionate: float = 5.0
    # Per-episode cap on the *cumulative* proportional bonus. Without a cap, a
    # fixed low-force policy can pin the attacker in an early stage where its
    # action is "correct" and farm ``reward_proportional`` every step for the
    # full horizon, inflating reward to oracle-like levels without ever
    # mitigating a real threat. The cap (default +5 x min_episode_length = +100)
    # preserves the early dense learning signal but removes the farming
    # incentive; once exhausted, correct play earns 0 from this term (penalties
    # still apply). ``None`` disables the cap (the uncapped case is itself a
    # reward-mis-specification ablation cell).
    proportional_bonus_cap: Optional[float] = 100.0

    # Reward mode. Two contracts:
    #
    # - ``"coupled"`` (alias ``"proportional"``): kill-chain-aware *shaping*. The
    #   per-step reward includes a proportionality term keyed on
    #   ``d = action - recommended_action(stage)`` — the SAME quantity that
    #   drives the attacker's tug-of-war transition. Under this contract the
    #   value-maximising policy reduces to "infer the stage, emit the matching
    #   action", i.e. a 5-way stage classifier. A supervised detector that acts
    #   on its prediction (RF-Acting) is exactly that classifier and is hard to
    #   beat in-distribution. Retained as the reward-shaping ablation cell.
    #
    # - ``"outcome"`` (alias ``"outcome_only"``): the per-step reward is ONLY the
    #   action cost; every stage-conditioned shaping term (proportionality,
    #   benign/recon guardrails, benign-passive bonus) is stripped. The learning
    #   signal then comes exclusively from realised OUTCOMES applied in
    #   ``step()``/``_step_at_impact``: the capped de-escalation bonus (paid only
    #   on an actual attacker pushdown), the terminal prevention bonus, the
    #   terminal IMPACT penalty/mitigation accounting, and the optional terminal
    #   FPR penalty. The reward is therefore NOT a function of matching the
    #   per-step ``recommended_action(stage)`` label, which de-couples the
    #   objective from the attacker dynamics and removes the privileged-shaping
    #   advantage of a supervised classifier. This is the primary deployment
    #   contract for the re-posed task.
    reward_mode: str = "outcome"

    # Reward — terminal & extreme cases
    impact_penalty: float = 200.0
    penalty_missed_impact: float = 150.0
    # The mitigation bonus is intentionally calibrated so that a *correct*
    # IMPACT response (ISOLATE) net-rewards the agent: -impact_penalty +
    # defense_success_bonus = -200 + 250 = +50. This makes the optimal
    # policy strictly better than the do-nothing baseline and lets the
    # G3.4 exit gate hold (recommended-action mean reward > 0). This bonus is
    # RESERVED for surviving a *terminal* IMPACT step; routine in-game
    # de-escalations are rewarded by the separate, smaller ``reward_deescalation``
    # term below (see PLAN §B6 and the de-escalation-farming fix).
    defense_success_bonus: float = 250.0
    # Per-step reward for a successful in-game de-escalation (pushing the
    # attacker down one kill-chain rung under a proportional response). This is
    # deliberately *decoupled* from ``defense_success_bonus`` (+250, reserved for
    # terminal IMPACT survival): reusing the large terminal bonus for every
    # routine pushdown over-rewards the raw *count* of de-escalations, making
    # "more attacks = more reward" and inflating the oracle ceiling. A small
    # positive value keeps de-escalation worth doing as a dense signal without
    # turning it into a farm. Its cumulative per-episode contribution is bounded
    # by ``deescalation_bonus_cap``.
    reward_deescalation: float = 15.0
    # Per-episode cap on the *cumulative* de-escalation reward (mirrors
    # ``proportional_bonus_cap``). ``None`` disables the cap (the uncapped case is
    # itself a reward-mis-specification ablation cell).
    deescalation_bonus_cap: Optional[float] = 150.0

    # Reward — benign-traffic guardrails
    reward_benign_passive: float = 10.0
    penalty_overreact_benign: float = 50.0
    penalty_block_benign: float = 100.0
    penalty_block_recon: float = 50.0

    # Lagrangian FPR penalty (review 2.2 / Direction 6)
    # At episode end, subtract beta * (benign_blocks / benign_steps).
    # beta=0.0 disables the penalty (default, preserves prior behaviour).
    fpr_penalty_beta: float = 0.0

    # -------------------------------------------------------------------------
    # Partial-observability redesign (sequential-decision re-pose).
    #
    # The legacy environment samples a CICIoT2023 feature row i.i.d. per step,
    # which makes a memoryless supervised classifier (RF-Acting) optimal by
    # construction: every observation fully reveals the stage, so there is no
    # value in integrating evidence over time. The three knobs below restore the
    # partial observability and temporal structure that real IoT intrusion
    # detection exhibits, so that a recurrent belief-state agent can outperform a
    # per-step classifier. All default to the legacy behaviour (byte-compatible).
    #
    # ``aliasing_rate`` (alpha): probability that a step emits a feature row from
    # an ADJACENT kill-chain stage instead of the true stage. A single RECON flow
    # can look benign; a single ACCESS flow can look like RECON. The stage is then
    # only reliably inferable from the *sequence*, not any single observation.
    # Applied identically to every consumer (RL and RF-Acting see the same
    # ambiguous stream), so it confers no information asymmetry. alpha=0 is the
    # legacy fully-observable anchor where the classifier is expected to win.
    aliasing_rate: float = 0.0
    # ``session_coherent``: when True, draw observations as a contiguous,
    # without-replacement run of same-stage rows (a session/campaign proxy) rather
    # than an independent uniform draw each step, so the per-step deltas carry
    # genuine temporal signal instead of being differences of unrelated flows.
    session_coherent: bool = False
    # ``no_post_transition_leak``: when True, the observation refreshed after the
    # attacker moves is drawn from the PRE-transition stage, so the just-happened
    # transition is not revealed one step early. Closes an observation leak that
    # weakened the partial-observability claim.
    no_post_transition_leak: bool = False
    # ``proximity_coupled``: RESTRAIN-style defense-tolerance dynamics that
    # replace the finite intrusion budget. The attacker's escalation pressure
    # scales with its proximity to the goal (lambda = stage / IMPACT): the closer
    # to IMPACT, the harder an under-forced defender finds it to hold the line.
    # Prevention is earned by holding the attacker below IMPACT for the entire
    # horizon (awarded at truncation), not by draining a counter. This removes the
    # "any forcing policy prevents once the budget is small" degeneracy and the
    # "B is cherry-picked" critique.
    proximity_coupled: bool = True
    # Floor on the proximity-scaled under-force escalation probability, as a
    # fraction of ``p_up``. At stage RECON (lambda=0.25) escalation probability is
    # p_up * (proximity_min_escalation + (1-proximity_min_escalation)*lambda);
    # at MANEUVER (lambda=0.75) it is higher. Keeps early-stage escalation
    # non-trivial while making late-stage holding demanding.
    proximity_min_escalation: float = 0.4

    # Canonical reward-mode names and their accepted aliases. ``__post_init__``
    # normalises every alias to its canonical token so the rest of the code only
    # ever compares against the canonical set.
    _REWARD_MODE_ALIASES: ClassVar[dict[str, str]] = {
        "proportional": "coupled",
        "coupled": "coupled",
        "outcome_only": "outcome",
        "outcome": "outcome",
    }

    def __post_init__(self) -> None:
        # Normalise reward-mode aliases and fail fast on a typo. A silently
        # ignored bad ``reward_mode`` would fall through to coupled shaping and
        # corrupt the coupled-vs-decoupled ablation, so this must raise.
        canonical = self._REWARD_MODE_ALIASES.get(self.reward_mode)
        if canonical is None:
            valid = sorted(set(self._REWARD_MODE_ALIASES))
            raise ValueError(
                f"Unknown reward_mode {self.reward_mode!r}; " f"expected one of {valid}."
            )
        self.reward_mode = canonical


# =============================================================================
# ADVERSARIAL ENVIRONMENT
# =============================================================================


class AdversarialIoTEnv(gym.Env):
    """Gymnasium environment for adversarial IoT defense training.

    This environment implements a partially observable Markov decision
    process where the agent observes realized network features but
    cannot directly see the underlying attack stage.

        Attacker (first-order Markov chain):
        - Controls attack progression through Kill Chain stages
        - Samples kill-chain stage transitions from a first-order Markov chain

    Blue Team (RL Agent):
        - Observes window of feature vectors
        - Takes discrete defensive actions
        - Receives reward based on defense effectiveness

    Observation Space:
        Box of shape (window_size * num_features,) or
        (window_size * num_features * 2,) when delta features are enabled.

    Action Space:
        Discrete(5): OBSERVE, LOG, RESTRICT, BLOCK, ISOLATE

    Example:
        >>> env = AdversarialIoTEnv(dataset_path)
        >>> obs, info = env.reset()
        >>> obs, reward, terminated, truncated, info = env.step(2)

    .. warning::
       **Direct construction contract (Step-3 F2 / Step-8 doc-fix).**
       Calling ``AdversarialIoTEnv(dataset_path, ...)``
       directly builds a non-split-aware ``RealizationEngine`` (the
       constructor below instantiates ``RealizationEngine(
       dataset_path)`` with no ``split_manifest`` / ``allowed_indices``
       argument). This means the engine samples from the *full* row
       pool — it does NOT honour the dataset-prep OOD-exclusion or
        ``split="train"`` invariants the Stage Detector through Ablation & Robustness depend on.

       **Production callers must use one of**:

       - ``src.blue_team.env_factory.make_train_env(...)`` (sets
         ``split="train", exclude_ood=True`` and monkey-patches the
         engine post-construction via ``env._realization_engine =
         engine``); or
       - ``src.blue_team.env_factory.make_eval_env(...)`` (caller
         supplies the eval split — typically ``"val_balanced"`` for
          Blue-Team eval or ``"test_balanced"`` for benchmark / ablation).

       Direct ``AdversarialIoTEnv(...)`` construction is reserved for
       synthetic-data unit tests (see ``tests/test_adversarial_env.py``)
       and the hand-rolled smoke probe in
       ``scripts/benchmark/run_test_eval.py:_roll_deterministic`` (RF-
       Acting feature-dim probe). A future refactor could add an
       ``engine: Optional[RealizationEngine] = None`` injection seam
       to ``__init__`` so the factory could pass the engine in
       directly (eliminating the ``# type: ignore[attr-defined]``
       monkey-patch in ``env_factory.py``); deferred to post-thesis.
    """

    metadata = {"render_modes": ["human"]}

    def __init__(
        self,
        dataset_path: Union[str, Path],
        config: Optional[AdversarialEnvConfig] = None,
        render_mode: Optional[str] = None,
        device: str = "cpu",
    ) -> None:
        """Initialize the Adversarial Environment.

        Args:
            dataset_path: Path to processed dataset for realization.
            config: Environment configuration.
            render_mode: Rendering mode (optional).
            device: Device for realization/detector tensors (CPU-first).
        """
        super().__init__()

        self._config = config or AdversarialEnvConfig()
        self._render_mode = render_mode
        self._device = device

        # Attacker dynamics: first-order Markov chain over kill-chain stages.
        self._attacker = MarkovAttacker()

        # Load Realization Engine (for feature sampling)
        dataset_path = Path(dataset_path)
        self._realization_engine = RealizationEngine(dataset_path)

        # Get feature dimension from dataset
        self._num_features = self._realization_engine.num_features

        # Load optional frozen stage detector for stage-prediction ablation
        self._stage_detector: Any = None
        if self._config.stage_detector_path is not None:
            self._stage_detector = _load_stage_detector(Path(self._config.stage_detector_path))

        # Define observation space: flattened window of features (optionally with deltas)
        obs_multiplier = 2 if self._config.include_deltas else 1
        obs_dim = self._config.window_size * self._num_features * obs_multiplier
        if self._config.include_stage_pred:
            if self._stage_detector is None:
                raise ValueError("include_stage_pred=True requires stage_detector_path to be set")
            obs_dim += self._config.num_actions  # one-hot appended stage
        self.observation_space = spaces.Box(
            low=-np.inf,
            high=np.inf,
            shape=(obs_dim,),
            dtype=np.float32,
        )

        # Define action space: force continuum levels
        self.action_space = spaces.Discrete(self._config.num_actions)

        # Episode state (initialized in reset)
        self._step_count: int = 0
        self._current_attack_stage: int = 0
        self._attack_history: list[int] = []
        self._observation_window: list[np.ndarray] = []
        self._last_action: int = 0
        # Evasion-before-commit: did the defender just apply force this step?
        self._recent_block: bool = False
        self._rng: Optional[np.random.Generator] = None
        # environment-design: MTTC tracking & defender-driven de-escalation
        self._first_attack_step: Optional[int] = None
        self._compromise_step: Optional[int] = None
        self._defender_deescalations: int = 0
        # FPR-penalty accumulator (review 2.2 / Direction 6)
        self._benign_steps: int = 0
        self._benign_blocks: int = 0

        logger.info(
            f"AdversarialIoTEnv initialized: "
            f"obs_shape={self.observation_space.shape}, "
            f"actions={self._config.num_actions}, "
            f"features={self._num_features}"
        )

    # =========================================================================
    # Gymnasium API
    # =========================================================================

    def reset(
        self,
        *,
        seed: Optional[int] = None,
        options: Optional[dict[str, Any]] = None,
    ) -> tuple[np.ndarray, dict[str, Any]]:
        """Reset the environment to start a new episode.

        Args:
            seed: Random seed for reproducibility.
            options: Additional options (unused).

        Returns:
            Tuple of (observation, info).
        """
        super().reset(seed=seed)

        # Setup RNG
        if seed is not None:
            self._rng = np.random.default_rng(seed)
            # Also seed the realization engine
            self._realization_engine._rng = np.random.default_rng(seed)
            np.random.seed(seed)
        else:
            self._rng = np.random.default_rng()

        # Reset episode state
        self._step_count = 0
        self._last_action = 0
        self._recent_block = False
        self._first_attack_step = None
        self._compromise_step = None
        self._defender_deescalations = 0
        self._proportional_bonus_paid = 0.0
        self._deescalation_bonus_paid = 0.0
        self._benign_steps = 0
        self._benign_blocks = 0

        # Initialize attack sequence
        # Start with BENIGN or low-level attack
        self._current_attack_stage = 0  # BENIGN
        self._attack_history = [self._current_attack_stage]

        # Initialize observation window with BENIGN features
        self._observation_window = []
        for _ in range(self._config.window_size):
            features = self._realization_engine.sample(
                KillChainStage.BENIGN,
                aliasing_rate=self._config.aliasing_rate,
                session_coherent=self._config.session_coherent,
            )
            self._observation_window.append(features)

        # Build initial observation
        observation = self._build_observation()

        # Build info dict
        info = self._build_info()

        return observation, info

    def step(
        self,
        action: int,
    ) -> tuple[np.ndarray, float, bool, bool, dict[str, Any]]:
        """Execute one environment step.

        Lifecycle (environment-design v2):

        1. **IMPACT step.** If we entered this step already at IMPACT, this is
           the agent's final mitigation turn. Reward depends on action choice;
           the episode terminates regardless.
        2. **Decision-stage reward.** Reward is computed against
           ``decision_stage = previous_attack_stage`` and the IoTWarden
           recommended-action mapping. No dependence on the agent's previous
           action.
        3. **Attack progression.** The Markov attacker samples the next stage.
           When the agent chose BLOCK or ISOLATE at ACCESS+ stages, the env
           overrides this with a defender-driven de-escalation to BENIGN
           (with probability ``p_defender_deescalation``). On a successful
           override, ``defense_success_bonus`` is added to the reward.
        4. **Termination.** The episode terminates only when the new stage is
           IMPACT (the agent will get one final IMPACT step on the next
           call) — but for backwards compatibility we mark ``terminated`` on
           that step too via ``_check_terminated``. Truncation fires at
           ``max_steps``.
        """
        assert self.action_space.contains(action), f"Invalid action: {action}"

        self._step_count += 1
        previous_attack_stage = self._current_attack_stage

        # 1) Final mitigation turn at IMPACT — fixed reward shape, terminate.
        if previous_attack_stage == KillChainStage.IMPACT.value:
            return self._step_at_impact(action)

        # 2) Reward for this step is decided by stage at decision time.
        reward = self._calculate_reward(action, previous_attack_stage)
        self._track_benign_fpr(action, previous_attack_stage)

        # Record whether the defender just applied force, so the attacker can
        # react (evasion-before-commit) when it advances this step.
        self._recent_block = action >= 3  # BLOCK or ISOLATE

        # 3) Advance the attack.
        if self._config.tug_of_war:
            outcome = self._advance_tug_of_war(action, previous_attack_stage)
            if outcome == "defended":
                # Routine in-game de-escalation: rewarded by the small, capped
                # ``reward_deescalation`` term, NOT the large terminal
                # ``defense_success_bonus`` (which is reserved for surviving a
                # terminal IMPACT step). This decouples the dense pushdown signal
                # from terminal-survival accounting and stops de-escalation-count
                # farming from inflating the reward ceiling.
                reward += self._capped_deescalation_bonus()
        else:
            # Legacy v2 dynamics: autonomous Markov advance with a
            # probabilistic defender-driven de-escalation override.
            agent_forced_deescalation = self._maybe_defender_deescalation(
                action, previous_attack_stage
            )
            if agent_forced_deescalation:
                reward += self._config.defense_success_bonus
                outcome = "defended"
            else:
                self._advance_attack()
                outcome = "ongoing"

        # Lifecycle-floor clamp: real-world IMPACT requires time-to-execute.
        # Until the agent has had its grace period, the attacker is not allowed
        # to short-circuit the kill chain by jumping straight to IMPACT.
        # Concretely: any IMPACT transition before ``min_episode_length`` is
        # downgraded to MANEUVER. This both gives the agent a fair chance to
        # learn the multi-stage dynamics *and* matches the IoTWarden-style
        # threat model in which IMPACT is the consummation of MANEUVER, not
        # an instantaneous transition from RECON.
        if (
            self._current_attack_stage == KillChainStage.IMPACT.value
            and self._step_count < self._config.min_episode_length
        ):
            self._current_attack_stage = KillChainStage.MANEUVER.value
            # Keep the history consistent: replace the last entry rather than
            # appending a parallel one (the attacker only sees the visible chain).
            if self._attack_history:
                self._attack_history[-1] = self._current_attack_stage

        # MTTC bookkeeping — see _build_info() for the consumed fields.
        if (
            self._first_attack_step is None
            and self._current_attack_stage != KillChainStage.BENIGN.value
        ):
            self._first_attack_step = self._step_count
        if (
            self._compromise_step is None
            and self._current_attack_stage == KillChainStage.IMPACT.value
        ):
            self._compromise_step = self._step_count

        # 4) Refresh the observation window with a sample drawn from the stage
        # the attacker occupied *before* this transition was decided. Sampling
        # from ``previous_attack_stage`` (not the new stage) removes the
        # post-transition feature leakage: the agent must infer that the
        # attacker moved from the *evidence it accumulates over time*, rather
        # than reading the just-completed transition off the very next
        # observation. Under partial observability this is the realistic
        # condition — the defender never gets an instantaneous, noise-free
        # readout of the attacker's current stage.
        obs_stage = (
            previous_attack_stage
            if self._config.no_post_transition_leak
            else self._current_attack_stage
        )
        new_features = self._realization_engine.sample(
            KillChainStage(obs_stage),
            aliasing_rate=self._config.aliasing_rate,
            session_coherent=self._config.session_coherent,
        )
        self._observation_window.pop(0)
        self._observation_window.append(new_features)
        self._last_action = action

        # Termination: only IMPACT triggers it, and only after the
        # min_episode_length grace period has elapsed (otherwise the agent
        # never sees a multi-stage trajectory).
        impact_arrived = (
            self._current_attack_stage == KillChainStage.IMPACT.value
            and self._step_count >= self._config.min_episode_length
        )
        if impact_arrived and self._config.impact_is_terminal:
            # environment-design frozen contract (default).
            # Apply the terminal IMPACT penalty inline. The kill chain has
            # consummated this step; we do *not* hand the agent a separate
            # "_step_at_impact" turn for OBSERVE/LOG -> the missed defense
            # is precisely what the IMPACT penalty was designed to punish.
            # Strong defenses (BLOCK/ISOLATE) earn the partial mitigation
            # bonus; weak defenses (OBSERVE/LOG) take the missed-impact hit.
            reward -= self._config.impact_penalty
            if action >= 3:
                reward += self._config.defense_success_bonus
                outcome = "impact_mitigated"
            elif action <= 1:
                reward -= self._config.penalty_missed_impact
                outcome = "impact_missed"
            else:
                outcome = "compromised"
            terminated = True
        else:
            # Either IMPACT has not arrived OR impact_is_terminal=False.
            # When False and IMPACT just arrived this step, do NOT terminate
            # and do NOT apply the inline terminal reward — the agent will
            # get an explicit IMPACT-row decision on the *next* step via
            # ``_step_at_impact`` (path 1 at the top of step()). The
            # "ongoing"/"defended" outcome label set above is preserved
            # so the F9 ablation sees this step as a normal pre-IMPACT
            # step that *just happened* to land on IMPACT.
            terminated = False
        truncated = self._step_count >= self._config.max_steps

        # Proximity-coupled prevention: with no finite budget, the defender
        # wins by holding the attacker below IMPACT for the entire horizon.
        # When the episode truncates (max_steps reached) and the kill chain
        # never consummated, award the prevention bonus and label the outcome
        # "prevented" — the line was held. This only fires when no terminal
        # outcome was already set (outcome is still the in-flight label).
        if (
            self._config.proximity_coupled
            and truncated
            and not terminated
            and self._current_attack_stage < KillChainStage.IMPACT.value
            and outcome not in ("prevented", "impact_mitigated", "impact_missed", "compromised")
        ):
            reward += self._config.prevention_bonus
            outcome = "prevented"

        if terminated or truncated:
            reward = self._apply_episode_fpr_penalty(reward)

        observation = self._build_observation()
        info = self._build_info()
        info["outcome"] = outcome
        return observation, reward, terminated, truncated, info

    # ------------------------------------------------------------------ helpers

    def _step_at_impact(self, action: int) -> tuple[np.ndarray, float, bool, bool, dict[str, Any]]:
        """Handle the agent's final mitigation turn while the attack is at IMPACT."""
        action_cost = get_action_cost(action) * self._config.action_cost_scale
        reward = -(self._config.impact_penalty) - action_cost
        if action >= 3:  # BLOCK or ISOLATE — partial mitigation bonus
            reward += self._config.defense_success_bonus
            outcome = "impact_mitigated"
        elif action <= 1:  # OBSERVE or LOG — severe miss at IMPACT
            reward -= self._config.penalty_missed_impact
            outcome = "impact_missed"
        else:
            outcome = "impact_unmitigated"

        new_features = self._realization_engine.sample(
            KillChainStage.IMPACT,
            aliasing_rate=self._config.aliasing_rate,
            session_coherent=self._config.session_coherent,
        )
        self._observation_window.pop(0)
        self._observation_window.append(new_features)
        self._last_action = action
        if self._compromise_step is None:
            self._compromise_step = self._step_count

        reward = self._apply_episode_fpr_penalty(reward)
        observation = self._build_observation()
        info = self._build_info()
        info["outcome"] = outcome
        return observation, reward, True, False, info

    def _apply_episode_fpr_penalty(self, reward: float) -> float:
        """Subtract terminal FPR penalty if fpr_penalty_beta > 0."""
        if self._config.fpr_penalty_beta <= 0.0:
            return reward
        if self._benign_steps == 0:
            return reward
        fpr = self._benign_blocks / self._benign_steps
        return reward - self._config.fpr_penalty_beta * fpr

    def _track_benign_fpr(self, action: int, previous_stage: int) -> None:
        """Increment benign-step / benign-block counters."""
        if previous_stage == KillChainStage.BENIGN.value:
            self._benign_steps += 1
            if action >= 3:  # BLOCK or ISOLATE
                self._benign_blocks += 1

    def _advance_tug_of_war(self, action: int, previous_stage: int) -> str:
        """Advance the attacker under the tug-of-war dynamics (headline, v3).

        The next stage is a function of the proportionality gap between the
        defender's ``action`` and the stage-recommended action. See the
        ``tug_of_war`` config block for the full specification.

        Returns the step outcome label: ``"defended"`` (attacker pushed down a
        rung), ``"ongoing"`` (held or escalated), or ``"benign"`` (attacker
        dormant at BENIGN and not provoked into onset).
        """
        assert self._rng is not None  # invariant after reset
        stage = int(previous_stage)
        recommended = _recommended_action(stage)

        # --- BENIGN: the attacker is dormant but has its *own* initiative to
        # begin the campaign. Onset to RECON happens autonomously with
        # probability ``p_onset`` regardless of the defender's action — the
        # attacker is not waiting to be provoked. A defender over-reaction
        # (gap >= 2, i.e. RESTRICT/BLOCK/ISOLATE on benign traffic) does not
        # accelerate the kill chain here; it is simply wasteful (and penalised
        # by the benign guardrails in the reward). No de-escalation is possible
        # below BENIGN.
        if stage == KillChainStage.BENIGN.value:
            # Multi-rung onset: the attacker may open the campaign at RECON or,
            # less often, directly at ACCESS (a mid-chain start). A single draw
            # partitions [0,1): [0, p_onset) -> RECON, [p_onset, p_onset +
            # p_onset_access) -> ACCESS, remainder -> stay dormant.
            roll = self._rng.random()
            if roll < self._config.p_onset:
                self._current_attack_stage = KillChainStage.RECON.value
                self._attack_history.append(self._current_attack_stage)
                return "ongoing"
            if roll < self._config.p_onset + self._config.p_onset_access:
                self._current_attack_stage = KillChainStage.ACCESS.value
                self._attack_history.append(self._current_attack_stage)
                return "ongoing"
            # Stay benign.
            self._attack_history.append(self._current_attack_stage)
            return "benign"

        # --- Active attack stage (RECON..MANEUVER; IMPACT is handled by
        # _step_at_impact before we get here). The transition is governed by the
        # *signed* force difference d = action - recommended(stage):
        #
        #   d <= -1 (under-force, defender too weak)  -> ESCALATE   w.p. p_up
        #   d ==  0 (proportional, exactly right)     -> DE-ESCALATE w.p. p_down
        #   d >=  1 (over-force, wasteful)            -> HOLD (no climb)
        #
        # Under-defending therefore lets the attacker climb (real, autonomous
        # pressure: a passive defender loses), the exact response pushes it back
        # down, and over-forcing merely stalls it (and is penalised by the
        # benign / proportionality guardrails in the reward).
        d = action - recommended

        if d <= -1:
            # Under-force: the attacker advances toward IMPACT.
            #
            # Proximity-coupled mode (RESTRAIN-style): escalation pressure
            # scales with the attacker's proximity to its goal,
            # lambda = stage / IMPACT. The closer the attacker is to IMPACT the
            # harder an under-forced defender finds it to hold the line, so the
            # defender must become decisive near the end of the chain. With no
            # finite budget, prevention is earned by holding the attacker below
            # IMPACT for the full horizon (awarded at truncation), not by
            # draining a counter. Default (legacy) mode uses a flat p_up.
            p_up_eff = self._config.p_up
            if self._config.proximity_coupled:
                lam = stage / KillChainStage.IMPACT.value
                p_up_eff = self._config.p_up * (
                    self._config.proximity_min_escalation
                    + (1.0 - self._config.proximity_min_escalation) * lam
                )
            if self._rng.random() < p_up_eff:
                self._current_attack_stage = min(KillChainStage.IMPACT.value, stage + 1)
            self._attack_history.append(self._current_attack_stage)
            return "ongoing"

        if d == 0:
            # Proportional force -> probabilistic de-escalation. ISOLATE
            # de-escalates more reliably than BLOCK (real force gradient). On a
            # failed pushdown the attacker simply holds (it never climbs under a
            # correct response).
            p_down = self._config.p_down_isolate if action == 4 else self._config.p_down
            if self._rng.random() < p_down:
                self._current_attack_stage = max(0, stage - 1)
                self._attack_history.append(self._current_attack_stage)
                self._defender_deescalations += 1
                return "defended"
            self._attack_history.append(self._current_attack_stage)
            return "ongoing"

        # d >= 1: over-force -> the attacker holds (stalled, not advanced).
        # Mis-targeted (disproportionately heavy) force stalls the attacker but
        # does not de-escalate it: spraying ISOLATE at a low stage holds the
        # intrusion in place without pushing it down.
        self._attack_history.append(self._current_attack_stage)
        return "ongoing"

    def _capped_deescalation_bonus(self) -> float:
        """Return the reward for one successful in-game de-escalation.

        Yields ``reward_deescalation`` per pushdown but bounds the cumulative
        per-episode contribution at ``deescalation_bonus_cap`` (when set), so a
        policy cannot farm reward simply by racking up a large *count* of routine
        de-escalations. Once the cap is exhausted, further pushdowns earn 0 from
        this term.
        """
        bonus = self._config.reward_deescalation
        cap = self._config.deescalation_bonus_cap
        if cap is not None:
            bonus = min(bonus, max(0.0, cap - self._deescalation_bonus_paid))
        self._deescalation_bonus_paid += bonus
        return bonus

    def _maybe_defender_deescalation(self, action: int, previous_stage: int) -> bool:
        """Return True iff the agent's action forced a stage reset to BENIGN.

        The override fires when the agent picks BLOCK or ISOLATE at an active
        ACCESS+ attack stage and the configured probability allows it. On a
        successful override the env replaces the natural attack progression
        for this step.
        """
        if action < 3:  # OBSERVE / LOG / RESTRICT never trigger
            return False
        if previous_stage < KillChainStage.ACCESS.value:
            return False
        assert self._rng is not None  # invariant after reset
        if self._rng.random() >= self._config.p_defender_deescalation:
            return False
        # Override the natural attacker transition.
        self._current_attack_stage = KillChainStage.BENIGN.value
        self._attack_history.append(self._current_attack_stage)
        self._defender_deescalations += 1
        return True

    def render(self) -> None:
        """Render the environment state."""
        if self._render_mode == "human":
            print(
                f"Step {self._step_count}: "
                f"Attack Stage = {KillChainStage(self._current_attack_stage).name}, "
                f"Last Action = {ACTION_NAMES[self._last_action]}"
            )

    def close(self) -> None:
        """Clean up environment resources."""
        pass

    # =========================================================================
    # Internal Methods
    # =========================================================================

    def _advance_attack(self) -> None:
        """Advance attack sequence using the Markov attacker."""
        # Sample the next attack stage from the first-order Markov chain.
        if len(self._attack_history) >= 1:
            next_stage = self._attacker.sample_next(self._current_attack_stage, self._rng)
            current_stage = self._current_attack_stage
            # Evasion-before-commit: if the defender just applied force and the
            # attacker is still at a pre-trigger stage (RECON/ACCESS), it stalls
            # in anticipation instead of progressing. This is coupled to the
            # defender's action, unlike the random ``retreat_prob`` override.
            if (
                self._config.evasion_prob > 0.0
                and self._recent_block
                and current_stage in (KillChainStage.RECON.value, KillChainStage.ACCESS.value)
                and self._rng is not None
                and self._rng.random() < self._config.evasion_prob
            ):
                next_stage = current_stage  # stall (do not progress)
            # Non-monotonic stress-test: independently override with a
            # retreat to a random earlier stage (review 2.4.3).
            if (
                self._config.retreat_prob > 0.0
                and current_stage > 0
                and self._rng is not None
                and self._rng.random() < self._config.retreat_prob
            ):
                next_stage = int(self._rng.integers(0, current_stage))
            self._current_attack_stage = next_stage
            self._attack_history.append(next_stage)

    def _build_observation(self) -> np.ndarray:
        """Build observation from feature window."""
        # Stack window and flatten
        window_array = np.stack(self._observation_window, axis=0)
        if self._config.include_deltas:
            deltas = np.zeros_like(window_array)
            deltas[1:] = window_array[1:] - window_array[:-1]
            window_array = np.concatenate([window_array, deltas], axis=1)
        observation = window_array.flatten().astype(np.float32)
        # Stage-prediction ablation: append one-hot predicted stage
        if self._config.include_stage_pred:
            assert self._stage_detector is not None
            latest_row = self._observation_window[-1].reshape(1, -1)
            pred_stage = int(self._stage_detector.predict(latest_row)[0])
            one_hot = np.zeros(self._config.num_actions, dtype=np.float32)
            one_hot[pred_stage] = 1.0
            observation = np.concatenate([observation, one_hot])
        return observation

    def _build_info(self) -> dict[str, Any]:
        """Build info dictionary including environment-design telemetry.

        New keys (environment-design):

        - ``compromised`` (bool): True iff the attack reached IMPACT this
          episode.
        - ``mttc_steps`` (int | None): Steps from first non-BENIGN observation
          until IMPACT. ``None`` if the attack never started or never
          reached IMPACT.
        - ``defender_deescalations`` (int): How many times the defender
          successfully forced a stage reset to BENIGN this episode.
        - ``recommended_action`` (int): The IoTWarden-aligned recommended
          action for the *current* stage. Useful for downstream logging
          (e.g., proportionality histograms).
        """
        compromised = self._compromise_step is not None
        if compromised and self._first_attack_step is not None:
            mttc_steps: Optional[int] = self._compromise_step - self._first_attack_step
        else:
            mttc_steps = None

        return {
            "attack_stage": self._current_attack_stage,
            "attack_stage_name": KillChainStage(self._current_attack_stage).name,
            "step_count": self._step_count,
            "attack_history": list(self._attack_history),
            "last_action": self._last_action,
            "last_action_name": ACTION_NAMES[self._last_action],
            "compromised": compromised,
            "mttc_steps": mttc_steps,
            "first_attack_step": self._first_attack_step,
            "compromise_step": self._compromise_step,
            "defender_deescalations": self._defender_deescalations,
            "recommended_action": _recommended_action(self._current_attack_stage),
        }

    def _calculate_reward(self, action: int, previous_stage: int) -> float:
        """Per-step reward for one non-IMPACT step.

        The reward depends only on the decision-time stage and the action.
        Behaviour is governed by ``reward_mode`` (see ``AdversarialEnvConfig``):

        - ``"outcome"``: returns only ``- C_action``. All stage-conditioned
          shaping below is skipped; the learning signal comes from realised
          outcomes applied in ``step()``/``_step_at_impact``. This is the
          primary deployment contract.
        - ``"coupled"`` (default): adds the kill-chain-aware shaping terms:
          benign/recon guardrails, the benign-passive bonus, and the
          proportionality term (``+ reward_proportional`` when
          ``|action - recommended_action(stage)| ≤ 1`` else
          ``- penalty_disproportionate``). Retained as the reward-shaping
          ablation cell; under it the optimal policy reduces to stage
          classification.

        Args:
            action: Defensive action taken (0..4).
            previous_stage: Attack stage at decision time (the stage the
                agent saw when it picked ``action``).

        Returns:
            Scalar reward.
        """
        decision_stage = int(previous_stage)
        reward = 0.0

        # 1) Cost of action.
        reward -= get_action_cost(action) * self._config.action_cost_scale

        # Outcome contract: skip all stage-conditioned shaping (guardrails,
        # benign-passive bonus, proportionality core). Only the action cost
        # remains here; the learning signal comes from realised outcomes
        # (de-escalation bonus, prevention bonus, terminal IMPACT accounting,
        # FPR penalty) applied in step()/_step_at_impact. This de-couples the
        # objective from d = action - recommended(stage), so the task is no
        # longer reducible to per-step stage classification.
        if self._config.reward_mode == "outcome":
            return reward

        # 2) Asymmetric guardrails on extreme errors.
        if decision_stage == KillChainStage.BENIGN.value and action >= 2:
            reward -= self._config.penalty_overreact_benign
            if action >= 3:
                reward -= self._config.penalty_block_benign
        elif decision_stage == KillChainStage.RECON.value and action >= 3:
            reward -= self._config.penalty_block_recon
        if decision_stage == KillChainStage.IMPACT.value and action <= 1:
            # Normally _step_at_impact handles IMPACT, but keep a safety
            # net so a pathological caller doesn't escape the penalty.
            reward -= self._config.penalty_missed_impact

        # 3) Positive signal for the canonical "do nothing on benign" case.
        if decision_stage == KillChainStage.BENIGN.value and action <= 1:
            reward += self._config.reward_benign_passive

        # 4) Stage-action proportionality — the new core (B2 fix).
        recommended = _recommended_action(decision_stage)
        proportionality_gap = abs(action - recommended)
        if proportionality_gap <= 1:
            # Apply the per-episode cap so that a fixed low-force policy cannot
            # farm this bonus indefinitely by pinning the attacker in an early
            # stage. Penalties are never capped.
            cap = self._config.proportional_bonus_cap
            bonus = self._config.reward_proportional
            if cap is not None:
                remaining = cap - self._proportional_bonus_paid
                bonus = max(0.0, min(bonus, remaining))
            self._proportional_bonus_paid += bonus
            reward += bonus
        else:
            reward -= self._config.penalty_disproportionate

        return reward
